config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#show'
  devise_for :users 
  
  resources :users, only: :show do 
	resources :contacts, except: [:show, :index]
  end
  
  get '*path', to: redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

belongs_to :user
scope :work, -> { where(group: 'work') }
scope :friends, -> { where(group: 'friends') }
scope :family, -> { where(group: 'family') }
scope :services, -> { where(group: 'services') }

GROUPS = [ 'family', 'work', 'friends', 'services']
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :contacts, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_action :set_contact, except: [:new, :create]

  
  
  def new
    @contact = Contact.new
	@groups = Contact::GROUPS
  end

  def create
    @contact = Contact.new(check_params)
    @contact.user_id = current_user.id

	if @contact.save
      redirect_to user_path(current_user)
    else
      render "new"
    end
  end

  def edit
    @groups = Contact::GROUPS
	
  end

  def update
    if @contact.update(check_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @contact.destroy
    redirect_to user_path(current_user)
  end
  
   
  private

  def check_params
    params.require(:contact).permit(:name, :email, :phone, :importance, :group)
  end
  
  def set_contact
    @contact = Contact.find(params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@contacts = current_user.contacts
		@groups = Contact::GROUPS
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-4 text-center">
		</div>
  
		<div class="col-xs-4 text-center">
			<div class="contact">
<%= form_for [:user,@contact] do |f|%>
</br>
<p> <%= f.label :name %>
    <%= f.text_field :name %></p>
<p> <%= f.label :email %>
    <%= f.email_field :email %></p>
<p> <%= f.label :phone %>
    <%= f.text_field :phone %></p>
<p> <%= f.label :importance, "VIP" %>
    <%= f.check_box :importance %>
<p> <%= f.label :group %>
    <%= f.select :group, options_for_select(@groups) %>
<p>	<%= f.submit 'Submit', class:'btn btn-default'%>
	<button class="btn btn-default" type="submit"><%= link_to "Cancel", user_path(:user) %></button>
	<%end%>
</p>

			</div>
		</div>
	
		<div class="col-xs-4 text-center">
		</div>
	</div>
 </div>

app/views/contacts/edit.html.erb
<h2><strong>Edit Contact: <%= @contact.name%></strong></h2>

<%= render "form" %>

app/views/contacts/new.html.erb
<h2>New Contact</h2>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>MyContact</title>
			<%= csrf_meta_tags %>
			<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	</head>

	<body>
		<header class="navbar navbar-inverse">
			<div class="header">
				<div class="container-fluid">
					<div class="navbar-header">
						<div class="navi" <%= link_to(image_tag("star_gold.png", :alt => "logo", width: 50, height: 50), root_url) %> </div>
					</div>
    
					<ul class="nav navbar-nav">
						<% if user_signed_in? %>
							<li class="navbar-text">
								Hello, <%=current_user.email do %> 
								<span class="glyphicon glyphicon-user"/>
								<% end %>
							</li>	
	  
							<li class="navi">
								<%= link_to new_user_contact_path(current_user) do %>
								New contact&nbsp;
								<span class="glyphicon glyphicon-book"/>
								<% end %>
							</li>
						<% end %>
					</ul>
	
					<ul class="nav navbar-nav navbar-right">
						<% if user_signed_in? %>
							<li class="navi">
								<%= link_to user_registration_path, method: :delete do %>
								Delete profile&nbsp;
								<span class="glyphicon glyphicon-remove"/>
								<% end %>
							</li>
	  
							<li class="navi">
								<%= link_to destroy_user_session_path, method: :delete do %>
								<span class="glyphicon glyphicon-log-out"></span> Log out
								<% end %>
							</li>
						<% else %>
							<li class="navi">
								<%= link_to new_user_registration_path do %>
								<span class="glyphicon glyphicon-user"></span> Sign up
								<% end %>
							</li>
       
							<li class="navi">
								<%= link_to new_user_session_path do %>
								<span class="glyphicon glyphicon-log-in"></span> Login 
								<% end %>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
		</header>
  
 
		<div class="notice">
			<%= notice %>
		</div>
  
		<div class="alert"><%= alert %>
		</div>
			
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/users/_contact_group.html.erb
<div class="contact">
	<%= contact.name %> 
	<% if contact.importance %> <!--==true niepotrzebne -->
		<%= image_tag("star_gold.png", width: 25, height: 25) %> 
	<% else %>
		<%= image_tag("star_white.png", width: 25, height: 25) %>
	<% end %>
	</br>
	<span class="glyphicon glyphicon-envelope"></span> 
	<%= contact.email%> 
	<span class="glyphicon glyphicon-earphone"></span>
    <%= contact.phone %> 
	</br>
	
	<%= link_to 'Edit', edit_user_contact_path(contact.user, contact) %> 
    
	<%= link_to 'Delete', 
	     user_contact_path(contact.user, contact), 
		 method: :delete, 
		 data: { confirm: 'Are you sure?' }   %> 
</div>


app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <% @groups.each do |group| %>
      <div class="col-xs-3 text-center">
        <div class="list">
          <h2><%= group.humanize %></h2>
          <div>
            <% @contacts.send(group).each do |c| %> 
			<!-- było dla każdej grupy: 
			@contacts.family.each do |c| - użyta była nazwa scope 
			metoda send() wywołuje metodę, której nazwy nie znamy zanim nie uruchomi się kod
			tutaj: dla każdej grupy nazwą wywoływanej metody jest nazwa grupy-->
              <%= render 'contact_group', contact: c %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>